services:
  api:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./contracts.db
    volumes:
      - ./backend:/app

  web:
    working_dir: /app
    image: node:20
    command: sh -c "npm install && npm run dev"
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: "http://api:8000" # nome do serviço backend no Docker
    volumes:
      - ./frontend:/app
    depends_on:
      - api
